# Generated by Django 4.2.1 on 2023-05-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesTable',
        ),
    ]
