# Generated by Django 4.2.1 on 2023-05-15 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
